name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
          python-version: [3.6]
          django-version: [2.2, 2.3]
    steps:
      - uses: actions/checkout@v2

      - name: Install Django
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Run Tests
        run: python run_tests.py
